server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hotels-service
          uri: lb://hotels-service
          predicates:
            - Path=/hotels-service/**
          filters:
            - RewritePath=/hotels-service/(?<path>.*), /${path}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: eo2q5HbX4/yo1VXlIIO0SDoYM/fb5bOHhb8EZaCDjIE=
